[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.27"
ffi = true
fs_permissions = [{ access = "read", path = "./artifacts/"}]
gas_reports = ["*"]
optimizer_runs = 1000000

# fuzz settings
[profile.default.fuzz]
runs = 256
[profile.intense.fuzz]
runs = 10_000

[fmt]
line_length = 120
tab_width = 4
wrap_comments = true